# Generated by Django 5.1.3 on 2025-05-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='12c28ab8', max_length=8, unique=True),
        ),
    ]
