# Generated by Django 5.1.3 on 2025-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_city_user_country_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('transgender', 'Transgender'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of interests/hobbies', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages spoken', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('in_relationship', 'In a relationship'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('complicated', "It's complicated"), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
