# Generated by Django 5.2.1 on 2025-06-04 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_webhookendpoint_messageanalytics_messageexpiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant1', 'is_active'], name='messaging_c_partici_9e4114_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant2', 'is_active'], name='messaging_c_partici_15b097_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='messaging_c_created_1ea16c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_deleted'], name='messaging_m_convers_702f27_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='messaging_m_message_9677d2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'message_type'], name='messaging_m_convers_d70066_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='messaging_m_reply_t_db4fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='messageanalytics',
            index=models.Index(fields=['message'], name='messaging_m_message_e1df16_idx'),
        ),
        migrations.AddIndex(
            model_name='messageanalytics',
            index=models.Index(fields=['read_count'], name='messaging_m_read_co_33d9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', 'created_at'], name='messaging_m_user_id_223455_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementanalytics',
            index=models.Index(fields=['user'], name='messaging_u_user_id_3d303d_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementanalytics',
            index=models.Index(fields=['engagement_score'], name='messaging_u_engagem_31263c_idx'),
        ),
    ]
